#+TITLE: Intro To Bash Scripting

* Assignment

#+begin_src sh
foo=bar # Look there should be no spaces between foo and bar.
#+end_src

If we put write foo = bar it will act as if we are passing '=' and 'bar' as argument to foo command.

* Output

Bash provide mainly two function to  to output .

#+begin_src sh
echo $foo * echo is kind of limited because of escape sequence and platform dependent.
printf $foo * printf works liks C version of printf and a much mature and platform independent.
#+end_src

* Difference between ' and "

There are two ways of defining strings in bash.

#+begin_src sh
printf "This will expand $foo"
printf 'This will expand $foo'
#+end_src

* Logical Operators

These operators can we used in if...else and switch-case statement but they can be used to chain command also which make them unique and worth taking notes.

- ; :: used to chain command together

	#+begin_src sh
	ls ; printf "Listing out directory";
	#+end_src

For the next set of operators keep short circuiting of operators in mind.

- && :: used to chain command which will run if first command is true and doesn't run if first command fails.

	#+begin_src sh
	cd Documents && printf "We are in Document Directory"
	cd notExist && printf "We are in notExist Directory"
	#+end_src

- || :: used to chain command which will run if first command is false and doesn't run if first command true.

	#+begin_src sh
	cd Documents || printf "We are in Document Directory"
	cd notExist || printf "We are in notExist Directory"
	#+end_src

- & :: this can be used to perform something called parallel processing or run multiple command in parallel.

	#+begin_src sh
	sleep 5 & printf "All done"
	#+end_src

- man test : gives brief overview of values that you can use to compare value.

* Reserved Keywords

+ `$1` - `$9` :: represent 1 to 9 argument.
+ `$0` :: represent name of the script
+ `$?` :: represent error code of the last command.
	Error code 0(ie think in terms of binary representation on 0 , all bits are down) represent everything worked well and anything other than zero means there is some error with the program.
+ `$_` or `!!` :: represent previous last command.
+ `$$` ::  represent pid.

* Using Output

To use output of a command.

#+begin_src sh
printf "We are in $(pwd)"
#+end_src

* Redirection

[Bash Redirection Explained](https://catonmat.net/bash-one-liners-explained-part-three)
- 0 - Points to stdout
- 1 - Points to stdin
- 2 - Points to stderr

The special file /dev/null discards all data written to it.

#+begin_src sh
libreoffice &>/dev/null
libreoffice 1>/dev/null 2>&1
#+end_src

Use of stdin:

#+begin_src sh
cat <(ls) <(ls..)
#+end_src

* Unknown Interpreter

If location of interpreter in unknown then we can use env command :
#+begin_src sh
*!/usr/bin/env python OR *!/usr/bin/env bash
#+end_src

* Easy form of man

'tldr' are easy form of man pages which are intuitive and easy to use.

* String Manipulation

+ % :: When % is used in pattern ${variable%substring} it will return content of variable with the shortest occurance of substring deleted from back of variable.

* TODO Globbing
